[build-system]
requires = ['hatchling']
build-backend = 'hatchling.build'

[project]
name = 'pdquery'
version = '0.0.1'
authors = [
  { name='AJ Friend', email='ajfriend@gmail.com' },
]
description = 'todo'
readme = 'readme.md'
requires-python = '>=3.7'
classifiers = [
    'Programming Language :: Python :: 3',
    'Operating System :: OS Independent',
]

dependencies = [
  'pandas >= 1.0',
  'duckdb',
  'prql-python',
]

[project.urls]
'Homepage' = 'todo'

[project.optional-dependencies]
dev = [
    'pytest'
]

[tool.pytest.ini_options]
minversion = '6.0'
addopts = '--durations=10'
testpaths = [
    'tests',
]
